document.writeln("<!--顶部导航栏部分-->");
document.writeln("<div id=\'topNavigation\' style=\'width: 1366px\'>");
document.writeln("    <nav class=\'container navbar navbar-expand bg-secondary navbar-dark\' style=\'height: 56px\'>");
document.writeln("        <!-- Brand -->");
document.writeln("        <a class=\'navbar-brand\' href=\'http://localhost:8080/pfo/\' style=\'font-size: 25px\'>");
document.writeln("            PFO<span style=\'font-size: 15px\'>&#32online</span>");
document.writeln("        </a>");
document.writeln("");
document.writeln("        <!-- Toggler/collapsibe Button -->");
document.writeln("        <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#topNavigation-collapsibleNavbar\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("");
document.writeln("        <!-- Navbar links -->");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'topNavigation-collapsibleNavbar\'>");
document.writeln("            <ul class=\'navbar-nav\' style=\'margin-top: 7px;\'>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'/pfo/\'>首页</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'/pfo/html/exam/exam_bank.html\'>题库</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'/pfo/html/discussion/post_show.html?topicId=0\'>讨论区</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'/pfo/html/recruit/recruit_recommend.html\'>求职</a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("            <!--&lt;!&ndash;搜索框&ndash;&gt;-->");
document.writeln("            <!--<form class=\'form-inline ml-auto\'>-->");
document.writeln("                <!--<div class=\'form-group\'>-->");
document.writeln("                    <!--<input type=\'text\' class=\'form-control\' placeholder=\'Search\'>-->");
document.writeln("                <!--</div>-->");
document.writeln("            <!--</form>-->");
document.writeln("            <ul class=\'navbar-nav\' style=\'position: absolute;right: 100px\'>");
document.writeln("                <li style=\'display: flex\'>");
document.writeln("                    <!--            &lt;!&ndash;用户头像&ndash;&gt;-->");
document.writeln("                    <a id=\'userImg\' class=\'navbar-brand\' href=\'/pfo/html/user/user.html\' style=\'margin-left: 20px;\' hidden=\'hidden\'>");
document.writeln("                        <img class=\'ml-auto rounded-circle\' src=\'https://images.nowcoder.com/images/20190816/846402631_1565956032347_193E973C19D9E8AA76A1AFADA284FD99?x-oss-process=image/resize,m_mfit,h_100,w_100\' alt=\'Logo\' style=\'width:40px;border: 2px white solid;\'>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li style=\'display: flex\'>");
document.writeln("                    <!--用户消息-->");
document.writeln("                    <div id=\'userMessage\' class=\'navbar-brand\'>");
document.writeln("                        <div style=\'float: left\'>");
document.writeln("                            <img src=\'/pfo/img/logo/userMessage.svg\' onclick=\'showUserMessage()\' alt=\'\' style=\'width: 1.7em\'>");
document.writeln("                        </div>");
document.writeln("                        <div id=\'userMessageNum\' style=\'float: left;color: red\'>0</div>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li style=\'display: flex\'>");
document.writeln("                    <!--Navbar text-->");
document.writeln("                    <div id=\'userOption\' class=\'navbar-text navbar-brand\' style=\'font-size: 1rem\'>");
document.writeln("                        <!--登录或未登录操作-->");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </nav>");
document.writeln("</div>");
document.writeln("<!--悬浮状态信息框-->");
document.writeln("<div id=\'Status\'>");
document.writeln("    <div style=\'text-align: center;display: flex;justify-content: center;z-index: 20000\'>");
document.writeln("        <div id=\'logInfo\' class=\'alert alert-success alert-dismissible fade show\' style=\'width: 200px\'>");
document.writeln("            <strong id=\'StatusInfo\'></strong>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
