document.writeln("<!--底部栏-->");
document.writeln("<nav id=\'footer-box\' class=\'navbar navbar-expand-sm bottom\' style=\'background-color:#6c757d\'>");
document.writeln("    <div class=\'col-sm-3\'>");
document.writeln("        <ul id=\'ft-nav\' class=\'navbar-nav\'>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("                <img class=\'qq-code\' src=\'/pfo/img/logo/PFO开发组群聊二维码.png\'>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <div class=\'col-sm-4\'>");
document.writeln("        <!-- Navbar text-->");
document.writeln("        <span id=\'ft-text\' class=\'navbar-text\' style=\'color: #D4D2D2;\'>");
document.writeln("        Practice For Offer");
document.writeln("        <p>笔试面试备战交流社区</p>");
document.writeln("        <img src=\'/pfo/img/logo/QQ.png\'>");
document.writeln("        <img src=\'/pfo/img/logo/微信.png\'>");
document.writeln("        <img src=\'/pfo/img/logo/git.png\'>");
document.writeln("        <img src=\'/pfo/img/logo/知乎.png\'>");
document.writeln("  </span>");
document.writeln("    </div>");
document.writeln("    <div class=\'col-sm-5\'>");
document.writeln("        <div class=\'ft-main\'>");
document.writeln("            <div class=\'justify-content-center\'>");
document.writeln("                <ul class=\'ft-links\'>");
document.writeln("                    <li><a href=\'#\'>关于我们</a></li>");
document.writeln("                    <li><a href=\'#\'>加入我们</a></li>");
document.writeln("                    <li><a href=\'#\'>意见反馈</a></li>");
document.writeln("                    <li><a href=\'#\'>企业服务</a></li>");
document.writeln("                    <li><a href=\'#\'>联系我们</a></li>");
document.writeln("                    <li><a href=\'#\'>免责声明</a></li>");
document.writeln("                    <li><a href=\'#\'>友情链接</a></li>");
document.writeln("                </ul>");
document.writeln("                <ul class=\'webrights\'>");
document.writeln("                    <li>公司地址：</li>");
document.writeln("                    <li>联系方式：(电话) <span class=\'contact-email\'>邮箱</span></li>");
document.writeln("                    <li>PFO开发组©<span id=\'jsNCPageFooterYear\'>2019</span> All rights reserved</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</nav>");